spring:
  data:
    mongodb:
      username: user
      password: p@ssw0rd
      additional-hosts: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090